---
title: "Meta RL analyses"
output: html_notebook
---

```{r}
library(tidyverse)
```

```{r}
num_runs = 10
results_dir = "results/paper_results/"

result_subdirs = c(# "nometa",# "nometa_su_heldout", "nometa_random_holdout_longer", "nometa_only_one",  "nometa_only_one_ho",
                   "basic", #"basic_su_heldout", 
                   "basic_random_holdout_longer") # "basic_only_one", "basic_only_one_ho")
                   
language_result_subdirs = c(                  
  "meta_batch_64", "meta_batch_128", "meta_batch_256",
  #"language", "language_simplified",
  "language_noncompositional", "language_simplified", # "language_meta_nontoggling",
  "language_noncompositional_old", "language_simplified_random_holdout",
  "language_mb_128_ne_15","language_mb_128_ne_20")

joint_result_subdirs = c("joint_lnex_mb_256_ne_20",
                         "joint_lnex_mb_256_ne_10",
                         "joint_lnex_mb_256_ne_5",
                         "joint_lnex_lw_mb_256_ne_10",
                         "joint_lnex_lw_mb_128_ne_10",
                         "joint_lnex_lw_mb_128_ne_5")

result_subdirs = c(result_subdirs, language_result_subdirs, joint_result_subdirs)

name_run_type = function(run_type) { # names for plotting
  case_when(run_type == "basic" ~ "Targeted 10% holdout",
            run_type == "basic_random_holdout_longer" ~ "Random 50% holdout",
            run_type == "language_noncompositional_old" ~ "Old language (targeted 10%)",
            run_type == "language_simplified" ~ "Old language (targeted 10%)",
            run_type == "meta_batch_128" ~ "Language (targeted 10%)",
            run_type == "language_simplified_random_holdout" ~ "Language (random 50%)",
            T ~ run_type)
}

name_game_type = function(game) {
  case_when(game == "high_card" ~ "High card",
            game == "straight_flush" ~ "Straight flush",
            game == "match" ~ "Match",
            game == "sum_under" ~ "Blackjack",
            game == "pairs_and_high" ~ "Pairs",
            T ~ game)
}


name_meta_task = function(meta_task) {
  case_when(meta_task == "toggle_losers" ~ "Losers",
            meta_task == "toggle_suits_rule" ~ "Suits > rank",
            meta_task == "toggle_black_valuable" ~ "Switch suits",
            T ~ meta_task)
}

new_game_strs = c("game_straight_flush_l_1_bv_0_sr_0",
                  "game_straight_flush_l_1_bv_1_sr_0",
                  "game_straight_flush_l_1_bv_0_sr_1",
                  "game_straight_flush_l_1_bv_1_sr_1")

new_game_strs_su_heldout = c("game_sum_under_l_1_bv_0_sr_0",
                             "game_sum_under_l_1_bv_1_sr_0",
                             "game_sum_under_l_1_bv_0_sr_1",
                             "game_sum_under_l_1_bv_1_sr_1")

new_game_strs_only_one = c('game_straight_flush_l_0_bv_1_sr_1', 'game_straight_flush_l_0_bv_1_sr_0', 'game_straight_flush_l_0_bv_0_sr_1', 'game_straight_flush_l_1_bv_0_sr_0', 'game_straight_flush_l_1_bv_1_sr_0', 'game_straight_flush_l_1_bv_0_sr_1', 'game_straight_flush_l_1_bv_1_sr_1')

new_game_strs_only_one_ho = c('game_straight_flush_l_1_bv_0_sr_0')

new_game_strs_random_heldout = c('game_match_l_0_bv_0_sr_1', 'game_match_l_0_bv_1_sr_1', 'game_pairs_and_high_l_1_bv_1_sr_0', 'game_high_card_l_0_bv_1_sr_1', 'game_straight_flush_l_1_bv_0_sr_1', 'game_straight_flush_l_0_bv_0_sr_0', 'game_pairs_and_high_l_0_bv_1_sr_1', 'game_straight_flush_l_1_bv_0_sr_0', 'game_match_l_1_bv_0_sr_1', 'game_pairs_and_high_l_0_bv_1_sr_0', 'game_pairs_and_high_l_1_bv_0_sr_0', 'game_sum_under_l_1_bv_0_sr_0', 'game_sum_under_l_0_bv_1_sr_0', 'game_high_card_l_1_bv_0_sr_1', 'game_sum_under_l_0_bv_0_sr_0', 'game_pairs_and_high_l_0_bv_0_sr_1', 'game_sum_under_l_1_bv_0_sr_1', 'game_match_l_1_bv_1_sr_1', 'game_sum_under_l_0_bv_1_sr_1', 'game_straight_flush_l_1_bv_1_sr_1')


meta_mapping_tasks = c("toggle_losers", "toggle_black_valuable", "toggle_suits_rule")
meta_classification_tasks = c("is_losers", "is_black_valuable", "is_suits_rule",
                              "is_high_card", "is_match", "is_straight_flush", "is_pairs_and_high", "is_sum_under")
```

# utils and setup

```{r}
load_d = function(results_dir, result_subdirs, num_runs, file_type) {
  d = data.frame()
  for (run_i in 0:(num_runs-1)) {
    for (result_subdir in result_subdirs) {
      filename = sprintf("%s%s/run%i_%s.csv", results_dir, result_subdir, run_i, file_type)
      if (!file.exists(filename)) {
        next
      }
      this_d = read.csv(filename, header=T) %>%
        mutate(run = run_i,
               run_type=result_subdir)
      d = bind_rows(d, this_d)
      }
  }
  d = d %>%
    mutate(named_run_type = name_run_type(run_type))
  return(d)
}
```

plot themes
```{r}
theme_set(theme_bw() + 
            theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
                  legend.margin = margin(0, 0, 0, 0), 
                  legend.box.margin = margin(0, 0, 0, 0)))
```

```{r}
name_var = function(var) { # var names for plotting
  case_when(var %in% c("is_new", "is_new_game") ~ "Held out?",
            var %in% c("game_type", "named_game_type") ~ "Game",
            var %in% c("run_type", "named_run_type") ~ "Run type",
#            var == "reward" ~ "Reward",
            grepl("reward", var) ~ "Average Reward",
            T ~ var)
  }

summary_plot = function(data,  x_var, y_var, color_var, optimal_baseline_data=NULL, other_baseline_data=NULL, palette="Set2", continuous_x=F) {
  
  p = ggplot(data, aes_string(x=x_var, y=y_var, color=color_var)) +  
    geom_hline(yintercept=0., linetype=2, alpha=0.5) +
    geom_point(stat="summary", fun.y=mean, size=2) +
    scale_color_manual(values=c("#555093", "#f38f22")) 
  
  if (!is.null(optimal_baseline_data)) {
    p = p + 
      annotate("segment",
               x=(1:5)-0.5, xend=(1:5)+0.5,
               y=optimal_baseline_data$expected_reward,
               yend=optimal_baseline_data$expected_reward,
               linetype=1, alpha=0.33) 
  }
  
  if (!is.null(other_baseline_data)) {
    # get rid of runs that aren't in data
    run_types_included = data %>% pull(named_run_type) %>% unique()
    other_baseline_data = other_baseline_data %>%
      filter(named_run_type %in% run_types_included)
    
    p = p + 
      geom_spoke(data=other_baseline_data,
                 aes_string(x=x_var, y="expected_reward", angle=0, radius=1),
                 linetype=2, alpha=0.5,
                 position=position_nudge(x=-0.5)) 
  }
 
  if (continuous_x) {
    p = p + 
      geom_line(stat="summary", fun.y=mean, size=2) 
  }
  
  p = p + 
    geom_point(stat="summary", fun.y=mean, size=2) +
    geom_errorbar(stat="summary", 
                  fun.data="mean_cl_boot",
                  width=0.4) +
#    scale_color_brewer(palette=palette) +
    labs(x=name_var(x_var), y=name_var(y_var)) +
    guides(color=guide_legend(title=NULL))
  
  return(p)
}
```

```{r}
check_if_new_game = function(run_type, game_str) {
  case_when(grepl("su_heldout", run_type) ~ game_str %in% new_game_strs_su_heldout,
            grepl("only_one$", run_type) ~ game_str %in% new_game_strs_only_one,
            grepl("only_one_ho", run_type) ~ game_str %in% new_game_strs_only_one_ho,
            grepl("random", run_type) ~ game_str %in% new_game_strs_random_heldout,
            T ~ game_str %in% new_game_strs)
}
```


```{r}
baseline_data = read_csv("baseline_data.csv") %>%
  mutate(game_type = str_extract(game, "high_card|match|straight_flush|pairs_and_high|sum_under"),
         losers = grepl("l_1", game),
         black_valuable = grepl("bv_1", game),
         suits_rule = grepl("sr_1", game),
         named_game_type = name_game_type(game_type))
```
```{r}
optimal_baselines = baseline_data %>% 
  filter(policy == "optimal") %>%
  group_by(game_type, named_game_type) %>%
  summarize(expected_reward = mean(expected_reward)) %>%
  ungroup() %>%
  arrange(named_game_type)
```

And "baselines" which show the performance using strategy from most correlated prior game

```{r}
most_correlated_baselines = crossing(run_type=result_subdirs, baseline_data) %>%
  mutate(is_new_game = check_if_new_game(run_type, game)) %>%
  filter((!is_new_game & policy == "optimal") | (policy != "optimal" & !check_if_new_game(run_type, policy))) %>%
  group_by(run_type, game, is_new_game, game_type, losers, black_valuable, suits_rule) %>%
  summarize(optimal_expected_reward = max(expected_reward)) %>%
  group_by(run_type, game_type, is_new_game) %>%
  summarize(expected_reward = mean(optimal_expected_reward)) %>%
  mutate(is_new_game = factor(is_new_game, levels=c(F, T), labels=c("Trained", "Held out")),
         named_run_type = name_run_type(run_type),
         named_game_type = name_game_type(game_type))

```



# meta-learning tests

```{r}
reward_d = load_d(results_dir, result_subdirs, num_runs, "new_rewards")

reward_d = reward_d %>%
  mutate(is_su_ho=grepl("su_heldout", run_type),
         is_only_one=grepl("only_one$", run_type),
         is_only_one_ho=grepl("only_one_ho", run_type),
         is_random_ho=grepl("random", run_type),
         is_default=!(is_su_ho | is_random_ho | is_only_one | is_only_one_ho)) %>%
  gather(game_str, reward, starts_with("game")) %>%
  mutate(game_type = str_extract(game_str, "high_card|match|straight_flush|pairs_and_high|sum_under"),
         losers = grepl("l_1", game_str),
         black_valuable = grepl("bv_1", game_str),
         suits_rule = grepl("sr_1", game_str),
         is_new_game = check_if_new_game(run_type, game_str),
         is_new_game = factor(is_new_game, labels=c("Trained", "Held out")),
         named_game_type = name_game_type(game_type))
```

```{r}
avg_reward_d = reward_d %>%
  select(-game_str) %>%
  filter(epoch == 0) %>%
  group_by(run_type, game_type, named_game_type, is_new_game) %>%
  summarize(avg_reward = mean(reward), sd_reward=sd(reward),
            se_reward = sd_reward/sqrt(n()), 
            ci_lo = avg_reward - 1.96*se_reward, 
            ci_hi = avg_reward + 1.96*se_reward)
```

```{r}

# summary_plot(reward_d %>%
#                filter(epoch == 0),
#              "game_type", "reward", "is_new_game",
#              optimal_baselines) +
#   facet_wrap(. ~ named_run_type)
```

```{r}
summary_plot(reward_d %>%
               filter(epoch == 0,
                      run_type == "basic"),
             "named_game_type", "reward", "is_new_game",
             optimal_baselines,
             most_correlated_baselines %>%
               filter(run_type == "basic",
                      is_new_game == "Held out")) + 
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

ggsave("~/Documents/grad/res/psych/ARRR/figures/meta_RL/basic.png", width=5, height=3.5)
#ggsave("~/Documents/grad/res/psych/ARRR/figures/meta_RL/basic_random_holdout_half.png", width=5, height=3.5)
```

```{r}
summary_plot(reward_d %>%
               filter(epoch == 0,
                      run_type == "basic_random_holdout_longer"),
             "named_game_type", "reward", "is_new_game",
             optimal_baselines,
             most_correlated_baselines %>%
               filter(run_type == "basic_random_holdout_longer",
                      is_new_game == "Held out")) + 
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

#ggsave("~/Documents/grad/res/psych/ARRR/figures/meta_RL/basic.png", width=5, height=3)
ggsave("~/Documents/grad/res/psych/ARRR/figures/meta_RL/basic_random_holdout_half.png", width=5, height=3.5)
```

```{r}
summary_plot(reward_d %>%
               filter(epoch == 0,
                      run_type %in% c("basic", "basic_random_holdout_longer")),
             "named_game_type", "reward", "is_new_game",
             optimal_baselines,
             most_correlated_baselines %>%
               filter(is_new_game == "Held out")) +
  facet_wrap(. ~ named_run_type) + 
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
  
ggsave("writing/figures/basic_meta_learning.png", width=4.2, height=3)
```

```{r}
summary_plot(reward_d %>%
               filter(run_type %in% c("basic", "basic_random_holdout_longer", "meta_batch_128", "language_simplified_random_holdout")),
             "epoch", "reward", "is_new_game",
             continuous_x=T) +
  facet_wrap(. ~ named_run_type) +
  geom_smooth(method="lm")
  
#ggsave("writing/figures/basic_meta_learning_integrating_over_time.png", width=4.2, height=3)
```

```{r}
#avg_reward_d %>% filter(is_new_game)
```

```{r}
# ggplot(avg_reward_d %>% filter(is_new_game, run_type %in% c("basic", "nometa")), aes(x=run_type, fill=run_type, y=avg_reward)) +
#   geom_bar(stat="identity", position="dodge") +
#   geom_errorbar(aes(ymin=ci_lo, ymax=ci_hi), position="dodge", width=0.5) +
#   scale_fill_brewer(palette="Set1")
```

## sweeping batch sizes
```{r}
sweep_d = load_d(results_dir, result_subdirs, num_runs, "new_sweep_rewards")

sweep_d = sweep_d %>%
  
  mutate(is_su_ho=grepl("su_heldout", run_type),
         is_only_one=grepl("only_one$", run_type),
         is_only_one_ho=grepl("only_one_ho", run_type),
         is_random_ho=grepl("random", run_type),
         is_default=!(is_su_ho | is_random_ho | is_only_one | is_only_one_ho)) %>%
  gather(game_str, reward, starts_with("game")) %>%
  mutate(game_type = str_extract(game_str, "high_card|match|straight_flush|pairs_and_high|sum_under"),
         losers = grepl("l_1", game_str),
         black_valuable = grepl("bv_1", game_str),
         suits_rule = grepl("sr_1", game_str),
         is_new_game = check_if_new_game(run_type, game_str))
         
```

```{r}
avg_sweep_d = sweep_d %>%
  select(-game_str) %>%
  filter(epoch == 0) %>%
  group_by(run_type, named_run_type, size, game_type, is_new_game) %>%
  summarize(avg_reward = mean(reward), sd_reward=sd(reward),
            se_reward = sd_reward/sqrt(n()), 
            ci_lo = avg_reward - 1.96*se_reward, 
            ci_hi = avg_reward + 1.96*se_reward)
```

```{r}
ggplot(avg_sweep_d, aes(x=size, color=is_new_game, y=avg_reward)) +
  geom_point() +
  geom_line() +
  geom_errorbar(aes(ymin=ci_lo, ymax=ci_hi)) +
  scale_color_brewer(palette="Set2") +
  xlab("Meta Set Size") +
  facet_grid(game_type ~ named_run_type)
```

```{r}
ggplot(avg_sweep_d %>%
         filter(run_type %in% c("basic", "meta_batch_256", "joint_lnex_lw_mb_256_ne_10", "joint_lnex_lw_mb_128_ne_10")), aes(x=size, color=is_new_game, y=avg_reward)) +
  geom_point() +
  geom_line() +
  geom_errorbar(aes(ymin=ci_lo, ymax=ci_hi)) +
  scale_color_brewer(palette="Set2") +
  xlab("Meta Set Size") +
  facet_grid(game_type ~ run_type)

#ggsave("~/Documents/grad/res/psych/ARRR/figures/meta_RL/basic_sweeping.png", width=5, height=3)
```

```{r}
ggplot(avg_sweep_d %>% filter(run_type %in% c("basic", "meta_batch_256", "meta_batch_128", "meta_batch_64", "language_mb_128_ne_15", "joint_lnex_mb_256_ne_5", "joint_lnex_mb_256_ne_10"),
                              size < 200), aes(x=size, color=named_run_type, y=avg_reward)) +
  geom_point() +
  geom_line() +
  geom_errorbar(aes(ymin=ci_lo, ymax=ci_hi)) +
  scale_color_brewer(palette="Set1") +
  xlab("Meta Set Size") +
  facet_grid(game_type ~ is_new_game)
```

# language results

```{r}
language_d = load_d(results_dir, c(language_result_subdirs, joint_result_subdirs), num_runs, "new_language_rewards")

                   
language_d = language_d %>%
  mutate(is_su_ho=grepl("su_heldout", run_type),
         is_only_one=grepl("only_one$", run_type),
         is_only_one_ho=grepl("only_one_ho", run_type),
         is_random_ho=grepl("random", run_type),
         is_default=!(is_su_ho | is_random_ho | is_only_one | is_only_one_ho)) %>%
  gather(game_str, reward, starts_with("game")) %>%
  mutate(game_type = str_extract(game_str, "high_card|match|straight_flush|pairs_and_high|sum_under"),
         losers = grepl("l_1", game_str),
         black_valuable = grepl("bv_1", game_str),
         suits_rule = grepl("sr_1", game_str),
         is_new_game = check_if_new_game(run_type, game_str),
         is_new_game = factor(is_new_game, labels=c("Trained", "Held out")))
```

```{r}
ggplot(language_d %>%
         filter(epoch == 0,
                is_new_game),
       aes(x=run, y=reward, fill=as.factor(run))) +
  geom_hline(yintercept=0.,
             linetype=2,
             alpha=0.5) +
  geom_violin(position="dodge") +
  geom_point(aes(group=as.factor(run)),
             size=3,
             stat="summary", fun.y="mean",
             position=position_dodge(width=0.9)) +
  scale_color_brewer(palette="Set2") + 
  ylim(-0.6, 0.6) +
  labs(x="Run",
       y="Reward density on held-out tasks") + 
  guides(fill=guide_legend(title="Run")) +
  facet_wrap(~named_run_type)
#ggsave("writing/figures/language_basic_by_run.png", width=5, height=3.5)
```


```{r}
summary_plot(language_d %>%
               filter(epoch == 0),
             "game_type", "reward", "is_new_game",
             optimal_baselines) +
  facet_wrap(. ~ named_run_type) + 
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
#ggsave("writing/figures/language_basic.png", width=5, height=3.5)
#ggsave("~/Documents/grad/res/psych/ARRR/figures/meta_RL/crappy_language.png", width=5, height=3)
```

```{r}
summary_plot(language_d %>%
               filter(epoch == 0,
                      run_type %in% c("meta_batch_128", "language_simplified_random_holdout")),
             "game_type", "reward", "is_new_game",
             optimal_baselines,
             most_correlated_baselines %>%
               filter(run_type %in% c("meta_batch_128", "language_simplified_random_holdout"),
                      is_new_game == "Held out")) +
  facet_wrap(. ~ named_run_type) + 
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
#ggsave("writing/figures/language_basic.png", width=7, height=3.5)
ggsave("~/Documents/grad/res/psych/ARRR/figures/meta_RL/language_basic.png", width=7, height=3.5)
```
# joint language + examples


```{r}
joint_d = load_d(results_dir, joint_result_subdirs, num_runs, "new_joint_lnex_rewards")

                   
joint_d = joint_d %>%
  mutate(is_su_ho=grepl("su_heldout", run_type),
         is_only_one=grepl("only_one$", run_type),
         is_only_one_ho=grepl("only_one_ho", run_type),
         is_random_ho=grepl("random", run_type),
         is_default=!(is_su_ho | is_random_ho | is_only_one | is_only_one_ho)) %>%
  gather(game_str, reward, starts_with("game")) %>%
  mutate(game_type = str_extract(game_str, "high_card|match|straight_flush|pairs_and_high|sum_under"),
         losers = grepl("l_1", game_str),
         black_valuable = grepl("bv_1", game_str),
         suits_rule = grepl("sr_1", game_str),
         is_new_game = check_if_new_game(run_type, game_str))
```

```{r}
ggplot(joint_d %>%
         filter(epoch == 0,
                is_new_game),
       aes(x=run, y=reward, fill=as.factor(run))) +
  geom_hline(yintercept=0.,
             linetype=2,
             alpha=0.5) +
  geom_violin(position="dodge") +
  geom_point(aes(group=as.factor(run)),
             size=3,
             stat="summary", fun.y="mean",
             position=position_dodge(width=0.9)) +
  scale_color_brewer(palette="Set2") + 
  ylim(-0.6, 0.6) +
  labs(x="Run",
       y="Reward density on held-out tasks") + 
  guides(fill=guide_legend(title="Run")) +
  facet_wrap(~named_run_type)
```

```{r}
summary_plot(joint_d %>%
               filter(epoch == 0),
             "game_type", "reward", "is_new_game",
             optimal_baselines) +
  facet_wrap(. ~ named_run_type) + 
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
#ggsave("writing/figures/joint_lnex.png", width=5, height=3.5)
```

# meta mapping (true) evaluation


```{r}
meta_tasks = c("toggle_losers", "toggle_suits_rule", "toggle_black_valuable")
meta_baseline_unmapped_d = crossing(meta_task=meta_tasks,
                                    run_type=result_subdirs,
                                    baseline_data) %>%
  filter(case_when(meta_task == "toggle_losers" ~ game == gsub("l_0", "l_1", policy) | game == gsub("l_1", "l_0", policy), 
                   meta_task == "toggle_black_valuable" ~ game == gsub("bv_0", "bv_1", policy) | game == gsub("bv_1", "bv_0", policy), 
                   meta_task == "toggle_suits_rule" ~ game == gsub("sr_0", "sr_1", policy) | game == gsub("sr_1", "sr_0", policy), 
                   T ~ F)) %>%
  mutate(named_run_type = name_run_type(run_type),
         named_meta_task = name_meta_task(meta_task),
         is_new = check_if_new_game(run_type, game) | check_if_new_game(run_type, policy),
         is_new = factor(is_new, labels=c("Trained", "Held out"))) %>%
  group_by(run_type, named_run_type, meta_task, named_meta_task, is_new)  %>%
  summarize(expected_reward = mean(expected_reward)) 

```


```{r}
meta_d = load_d(results_dir, result_subdirs, num_runs, "new_meta_true_losses")

meta_d = meta_d %>%
  filter(epoch == 0) %>%
  mutate(is_su_ho=grepl("su_heldout", run_type),
         is_only_one=grepl("only_one$", run_type),
         is_only_one_ho=grepl("only_one_ho", run_type),
         is_random_ho=grepl("random", run_type),
         is_default=!(is_su_ho | is_random_ho | is_only_one)) %>%
  gather(map_str, reward, -c(run, run_type, named_run_type, epoch), -starts_with("is_")) %>%
  separate(map_str, c("meta_task", "source", "target"), sep="[\\.]+") %>%
  mutate(is_new = check_if_new_game(run_type, source) | check_if_new_game(run_type, target),
         is_new = factor(is_new, labels=c("Trained", "Held out")),
         named_meta_task = name_meta_task(meta_task))
```

```{r}
avg_meta_d = meta_d %>%
  group_by(run_type, named_run_type, run, meta_task, named_meta_task, is_new) %>%
  summarize(avg_reward = mean(reward)) %>%
  group_by(run_type, named_run_type, meta_task, named_meta_task, is_new) %>%
  summarize(avg_avg_reward = mean(avg_reward), sd_avg_reward = sd(avg_reward),
            se_reward = sd_avg_reward/sqrt(n()), 
            ci_lo = avg_avg_reward - 1.96*se_reward, 
            ci_hi = avg_avg_reward + 1.96*se_reward)
  
```

```{r}
ggplot(avg_meta_d, aes(x=meta_task, fill=is_new, y=avg_avg_reward)) +
  geom_bar(stat="identity", position="dodge") +
  geom_errorbar(aes(ymin=ci_lo, ymax=ci_hi), position="dodge") +
  scale_fill_brewer(palette="Set2") +
  facet_wrap(. ~ named_run_type)
```

```{r}
summary_plot(meta_d %>%
               filter(epoch == 0,
                      meta_task %in% c("toggle_losers", "toggle_black_valuable"),
                      run_type %in% c("basic", "basic_random_holdout_longer")),
             "named_meta_task", "reward", "is_new",
             other_baseline_data = meta_baseline_unmapped_d %>%
               filter(is_new == "Held out",
                      meta_task %in% c("toggle_losers", "toggle_black_valuable"))) +
  facet_wrap(. ~ named_run_type)  +
  guides(color=guide_legend(title=NULL)) +
  labs(x="Meta task", y="Average reward") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

#ggsave("~/Documents/grad/res/psych/ARRR/figures/meta_RL/basic_basic_random_meta.png", width=5, height=3.5)
ggsave("writing/figures/meta_mapping.png", width=4.2, height=3)
```

# language-induced meta mapping (true) evaluation

```{r}
lang_meta_d = load_d(results_dir, c(language_result_subdirs, joint_result_subdirs), num_runs, "new_language_meta_true_losses")

lang_meta_d = lang_meta_d %>%
  filter(epoch == 0) %>%
  mutate(is_su_ho=grepl("su_heldout", run_type),
         is_only_one=grepl("only_one$", run_type),
         is_only_one_ho=grepl("only_one_ho", run_type),
         is_random_ho=grepl("random", run_type),
         is_default=!(is_su_ho | is_random_ho | is_only_one)) %>%
  gather(map_str, reward, -c(run, run_type, named_run_type, epoch), -starts_with("is_")) %>%
  separate(map_str, c("meta_task", "source", "target"), sep="[\\.]+") %>%
  mutate(is_new = check_if_new_game(run_type, source) | check_if_new_game(run_type, target),
         is_new = factor(is_new, labels=c("Trained", "Held out")),
         named_meta_task=name_meta_task(meta_task))
```

```{r}
summary_plot(lang_meta_d %>%
               filter(epoch == 0),
             "meta_task", "reward", "is_new") +
  facet_wrap(. ~ named_run_type)  +
  guides(color=guide_legend(title=NULL)) +
  labs(x="Game type", y="Average reward") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
 #ggsave("writing/figures/language_meta_mapping.png", width=5, height=3.5)
```

```{r}
summary_plot(lang_meta_d %>%
               filter(epoch == 0,
                      meta_task %in% c("toggle_losers", "toggle_black_valuable"),
                      run_type %in% c("meta_batch_128", "language_simplified_random_holdout")) %>%
               mutate(named_run_type = factor(named_run_type, labels=c("Random 50% holdout", "Targeted 10% holdout"))),
           
             "named_meta_task", "reward", "is_new",
             other_baseline_data = meta_baseline_unmapped_d %>%
               filter(is_new == "Held out",
                      meta_task %in% c("toggle_losers", "toggle_black_valuable"))) +
  facet_wrap(. ~ named_run_type)  +
  guides(color=guide_legend(title=NULL)) +
  labs(x="Meta task", y="Average reward") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

#ggsave("~/Documents/grad/res/psych/ARRR/figures/meta_RL/language_meta.png", width=7, height=3.5)
ggsave("writing/figures/language_meta_mapping.png", width=4.2, height=3)

```

# embeddings
```{r}
library(tsne)
```

```{r}
#for (result_subdir in result_subdirs) {
#  for (emb_type in c("guess", "final")) {
for (result_subdir in c("basic")) {
  for (emb_type in c("final")) {
    emb_d = data.frame()
    for (run_i in 0:(num_runs-1)) {
      filename = sprintf("%s%s/run%i_%s_embeddings.csv", results_dir, result_subdir, run_i, emb_type)
      if (!file.exists(filename)) {
        next
      }
      this_d = read.csv(filename, header=T)
      this_d$run = run_i
      emb_d = bind_rows(emb_d, this_d)
    }
    
    set.seed(0) # reproducible tsne
    pcs = prcomp(emb_d %>% select(-dimension, -run, -starts_with("is"), -starts_with("toggle")), center=T, scale=T)
    pc_d = data.frame(pcs$rotation)
    pc_d$task = row.names(pc_d)
    pc_d = pc_d %>% 
      mutate(game_type = str_extract(task, "high_card|match|straight_flush|pairs_and_high|sum_under"),
             losers = grepl("l_1", task),
             black_valuable = grepl("bv_1", task),
             suits_rule = grepl("sr_1", task),
             named_game_type = name_game_type(game_type))
    ggplot(pc_d, aes(x=PC1, y=PC2, shape=named_game_type, color=losers, size=black_valuable)) +
      geom_point() +
      scale_color_brewer(palette="Dark2") + 
      labs(x="Dimension 1", y="Dimension 2") +
      guides(size=guide_legend(title="Switch suits"),
             shape=guide_legend(title="Game"),
             color=guide_legend(title="Losers"))
    ggsave(sprintf("plots/%s_PCA_basic_%s.png", result_subdir, emb_type), width=7, height=7)
    
    ts = data.frame(tsne(emb_d %>% select(-dimension, -run, -starts_with("is"), -starts_with("toggle")) %>% as.matrix() %>% t(),
                         perplexity=5,
                         initial_dims=10))
    ts$task = pc_d$task
    ts = ts %>% 
      mutate(game_type = str_extract(task, "high_card|match|straight_flush|pairs_and_high|sum_under"),
             losers = grepl("l_1", task),
             black_valuable = grepl("bv_1", task),
             suits_rule = grepl("sr_1", task),
             named_game_type = name_game_type(game_type))
    ggplot(ts, aes(x=X1, y=X2, shape=named_game_type, color=losers, size=black_valuable)) +
      geom_point() + 
      scale_color_brewer(palette="Dark2") + 
      labs(x="Dimension 1", y="Dimension 2") +
      guides(size=guide_legend(title="Switch suits"),
             shape=guide_legend(title="Game"),
             color=guide_legend(title="Losers"))
    ggsave(sprintf("plots/%s_tsne_basic_%s.png", result_subdir, emb_type), width=7, height=7)
    
    set.seed(0) # reproducible tsne
    pcs = prcomp(emb_d %>% select(-dimension, -run, -contains("suits_rule")), center=T, scale=T)
    pc_d = data.frame(pcs$rotation)
    pc_d$task = row.names(pc_d)
    ggplot(pc_d, aes(x=PC1, y=PC2, color=task)) +
      geom_point() +
      geom_text(aes(label=task)) +
      guides(color=F)
    ggsave(sprintf("plots/%s_PCA_full_%s.png", result_subdir, emb_type), width=7, height=7)

    ts = data.frame(tsne(emb_d %>% select(-dimension, -run, -contains("suits_rule")) %>% as.matrix() %>% t(),
                         perplexity=5,
                         initial_dims=10))
    ts$task = row.names(pc_d)
    ts = ts %>%
      mutate(is_meta = grepl("is_|toggle_", task),
             meta_type = ifelse(is_meta, str_extract(task, "toggle|is"), NA),
             game_type = str_extract(task, "high_card|match|straight_flush|pairs_and_high|sum_under"),
             losers = grepl("l_1", task),
             black_valuable = grepl("bv_1", task),
             suits_rule = grepl("sr_1", task),
             named_game_type = name_game_type(game_type),
             type_var = ifelse(is_meta, task, "basic"),
             type_var = factor(type_var,
                               levels=c('basic', 'is_high_card', 'is_straight_flush', 'is_match', 'is_pairs_and_high', 'is_sum_under', 'is_suits_rule', 'is_losers', 'is_black_valuable', 'toggle_suits_rule', 'toggle_losers', 'toggle_black_valuable'),
                               labels=c('Basic', 'is_high_card', 'is_poker', 'is_match', 'is_pairs', 'is_blackjack', 'is_suits_rule', 'is_losers', 'is_switched_suits', 'toggle_suits_rule', 'toggle_losers', 'toggle_switch_suits'))
             )
    ggplot(ts, aes(x=X1, y=X2, color=type_var, alpha=is_meta)) +
      geom_point() +
      geom_text(data=ts %>% filter(is_meta),
                aes(label=type_var),
                position=position_nudge(y=40, x=-100),
                size=4) +
      scale_alpha_manual(values=c(0.33, 1)) + 
      scale_color_brewer(palette="Set3") + 
      labs(x="Dimension 1", y="Dimension 2") +
      guides(alpha=F,
             color=guide_legend(title="Task"))
    ggsave(sprintf("plots/%s_tsne_full_%s.png", result_subdir, emb_type), width=7, height=6)
  }
}
```

```{r}
# emb_type = "guess"
# emb_d = data.frame()
# for (meta_task in c("None", meta_mapping_tasks)) {
#   for (run_i in 0:(num_runs-1)) {
#     if (meta_task == "None") {
#       filename = sprintf("%srun%i_%s_embeddings.csv",results_dir, run_i, emb_type)
#       if (!file.exists(filename)) {
# #          print(paste("Skipping", filename, sep=" "))
#         next 
#       }
#       this_d = read.csv(filename, header=T)
#     } else {
#       filename = sprintf("%srun%i_%s_%s_embeddings.csv", results_dir, run_i, meta_task, emb_type)
#       if (!file.exists(filename)) {
# #          print(paste("Skipping", filename, sep=" "))
#         next 
#       }
#       this_d = read.csv(filename, header=T)
#     }
#     this_d$run = run_i
#     this_d$meta_task = meta_task
#     emb_d = bind_rows(emb_d, this_d)
#   }
# }
```
